# Generated by Django 5.0.3 on 2025-01-09 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owner', '0002_owner_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutsalFacility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=50)),
                ('number_of_pitches', models.IntegerField()),
                ('pitch_dimensions', models.CharField(max_length=50)),
                ('availability_start_time', models.TimeField()),
                ('availability_end_time', models.TimeField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_changing_room', models.BooleanField(default=False)),
                ('parking_facilities', models.CharField(blank=True, max_length=255, null=True)),
                ('water_availability', models.BooleanField(default=False)),
                ('event_capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futsal_facilities', to='Owner.owner')),
            ],
        ),
    ]
