# Generated by Django 5.0.3 on 2025-01-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsalfacility',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
