# Generated by Django 5.0.3 on 2025-01-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_futsalfacility_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsalfacility',
            name='cafeteria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='futsalfacility',
            name='equipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='futsalfacility',
            name='lights',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='futsalfacility',
            name='parking_facilities',
            field=models.BooleanField(default=False),
        ),
    ]
