# Generated by Django 5.0.3 on 2025-01-16 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_futsalfacility_cafeteria_futsalfacility_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futsalfacility',
            name='image_url',
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facilities.futsalfacility')),
            ],
        ),
    ]
