# Generated by Django 5.0.3 on 2025-01-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
